(() => {
  'use strict';
  if (location.pathname.startsWith('/admin')) return;
  const tokensKey = 'mtgx-access-tokens';
  const escapeHtml = (value) => String(value ?? '').replace(/[&<>"']/g, (char) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#039;' }[char]));
  const tokens = () => { try { return JSON.parse(localStorage.getItem(tokensKey) || '[]'); } catch (_) { return []; } };
  const saveToken = (token) => { const next = [...new Set([token, ...tokens()])].slice(0, 20); localStorage.setItem(tokensKey, JSON.stringify(next)); };
  const request = async (url, options = {}) => { const response = await fetch(url, { ...options, headers: { 'content-type': 'application/json', ...(options.headers || {}) } }); const body = await response.json(); if (!response.ok) throw new Error(body.detail || 'request'); return body; };
  const renderAccesses = async (root) => { const items = []; for (const token of tokens()) { try { items.push(await request(`/api/access/${encodeURIComponent(token)}`)); } catch (_) {} } root.innerHTML = items.length ? items.map((item) => `<article class="mtgx-access-item"><span class="mtgx-access-check">✓</span><div><strong>${escapeHtml(item.accessTitle || item.productName)}</strong><small>${escapeHtml(item.productName)} · ${escapeHtml(item.accessType || 'link')} · liberado em ${new Date(item.usedAt).toLocaleString('pt-BR')}</small>${item.note ? `<small>${escapeHtml(item.note)}</small>` : ''}</div><a href="${escapeHtml(item.deliveryUrl)}" target="_blank" rel="noopener noreferrer">Abrir produto ↗</a></article>`).join('') : '<div class="mtgx-access-empty">Nenhum produto liberado ainda. Use o código recebido após a confirmação do pagamento.</div>'; };
  const start = () => { const launcher = document.createElement('button'); launcher.className = 'mtgx-access-launcher'; launcher.type = 'button'; launcher.innerHTML = '<span>✓</span> ACESSAR PRODUTO'; launcher.setAttribute('aria-label', 'Validar código e acessar produto'); const modal = document.createElement('div'); modal.className = 'mtgx-access-modal'; modal.innerHTML = `<div class="mtgx-access-dialog" role="dialog" aria-modal="true" aria-labelledby="mtgx-access-title"><button class="mtgx-access-close" aria-label="Fechar">×</button><span class="mtgx-access-kicker">acesso / confirmação</span><h2 id="mtgx-access-title">Seu produto está pago?</h2><p>Digite o código enviado pelo ADM depois da confirmação do pagamento. Cada código libera um único acesso.</p><form class="mtgx-access-form"><label>Código de confirmação<input data-access-code placeholder="MTGX-ABC123-DEF456" autocomplete="one-time-code" spellcheck="false"></label><button type="submit">Validar e liberar produto</button></form><p class="mtgx-access-status" role="status"></p><div class="mtgx-access-list"><h3>Meus produtos liberados</h3><div data-access-items></div></div></div>`; document.body.append(launcher, modal); const close = () => modal.classList.remove('open'); launcher.onclick = () => { modal.classList.add('open'); renderAccesses(modal.querySelector('[data-access-items]')); modal.querySelector('[data-access-code]').focus(); }; modal.querySelector('.mtgx-access-close').onclick = close; modal.onclick = (event) => { if (event.target === modal) close(); }; modal.querySelector('.mtgx-access-form').onsubmit = async (event) => { event.preventDefault(); const input = modal.querySelector('[data-access-code]'); const status = modal.querySelector('.mtgx-access-status'); const button = modal.querySelector('button[type="submit"]'); const code = input.value.trim().toUpperCase(); if (!code) { status.textContent = 'Digite seu código de confirmação.'; return; } button.disabled = true; status.textContent = 'Validando código...'; try { const result = await request('/api/access/redeem', { method: 'POST', body: JSON.stringify({ code }) }); saveToken(result.accessToken); status.innerHTML = `${escapeHtml(result.product.accessTitle || 'Acesso liberado')}: <a href="${escapeHtml(result.product.deliveryUrl)}" target="_blank" rel="noopener noreferrer">abrir ${escapeHtml(result.product.name)} ↗</a>${result.product.note ? `<br><small>${escapeHtml(result.product.note)}</small>` : ''}`; input.value = ''; await renderAccesses(modal.querySelector('[data-access-items]')); } catch (error) { status.textContent = error.message.includes('utilizado') ? 'Este código já foi utilizado.' : 'Código inválido ou não encontrado.'; } button.disabled = false; }; };
  if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', start, { once: true }); else start();
})();
