(() => {
  const isAdmin = location.pathname.startsWith('/admin');
  const css = document.createElement('style');
  css.textContent = `.mtgx-ops-card{margin:18px 0;padding:18px;border:1px solid rgba(141,184,255,.2);border-radius:18px;background:linear-gradient(135deg,rgba(20,32,55,.72),rgba(7,11,20,.86));box-shadow:0 14px 38px rgba(0,0,0,.2)}.mtgx-ops-head{display:flex;align-items:flex-start;justify-content:space-between;gap:14px;margin-bottom:14px}.mtgx-ops-kicker{color:#8db8ff;font:700 10px ui-monospace,SFMono-Regular,Menlo,monospace;letter-spacing:.12em;text-transform:uppercase}.mtgx-ops-title{margin:5px 0 0;color:#f4f8ff;font-size:18px;font-weight:800}.mtgx-ops-state{padding:5px 8px;border:1px solid rgba(104,220,164,.32);border-radius:999px;color:#8ff0bb;background:rgba(66,190,126,.08);font:700 9px ui-monospace,SFMono-Regular,Menlo,monospace;white-space:nowrap}.mtgx-ops-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:9px}.mtgx-ops-toggle{display:flex;align-items:center;justify-content:space-between;gap:12px;padding:11px 12px;border:1px solid rgba(148,170,205,.16);border-radius:12px;background:rgba(255,255,255,.035);cursor:pointer}.mtgx-ops-toggle:hover{border-color:rgba(141,184,255,.45);background:rgba(141,184,255,.06)}.mtgx-ops-label{display:grid;gap:3px;color:#edf4ff;font-size:12px;font-weight:700}.mtgx-ops-help{color:#8fa3c0;font-size:10px;font-weight:500}.mtgx-ops-switch{position:relative;width:38px;height:22px;flex:0 0 38px;border-radius:999px;background:#29364c;transition:background .18s ease}.mtgx-ops-switch::after{content:'';position:absolute;top:3px;left:3px;width:16px;height:16px;border-radius:50%;background:#b8c8de;transition:transform .18s ease}.mtgx-ops-toggle.is-on .mtgx-ops-switch{background:#527fce}.mtgx-ops-toggle.is-on .mtgx-ops-switch::after{transform:translateX(16px);background:#fff}.mtgx-ops-message{width:100%;min-height:70px;margin-top:10px;padding:10px 12px;border:1px solid rgba(148,170,205,.16);border-radius:12px;background:rgba(0,0,0,.14);color:#dbe8fb;resize:vertical;font:500 12px inherit}.mtgx-ops-actions{display:flex;align-items:center;gap:10px;margin-top:10px}.mtgx-ops-save{padding:10px 14px;border:0;border-radius:10px;background:#a9caff;color:#08111f;font-weight:800;cursor:pointer}.mtgx-ops-save:disabled{opacity:.55;cursor:wait}.mtgx-ops-note{color:#8fa3c0;font-size:10px}@media(max-width:700px){.mtgx-ops-grid{grid-template-columns:1fr}.mtgx-ops-head{display:block}.mtgx-ops-state{display:inline-block;margin-top:10px}}`;
  document.head.appendChild(css);
  if (isAdmin) {
    const wait = (fn, tries = 80) => { if (fn()) return; if (tries) setTimeout(() => wait(fn, tries - 1), 250); };
    const key = () => sessionStorage.getItem('orvex-admin-key');
    const api = async (path, options = {}) => { const res = await fetch(path, { ...options, headers: { 'Content-Type': 'application/json', 'x-admin-key': key() || '', ...(options.headers || {}) } }); if (!res.ok) throw new Error(`HTTP ${res.status}`); return res.json(); };
    const mount = async () => {
      if (document.querySelector('.mtgx-ops-card') || !key()) return false;
      const host = document.querySelector('.admin-main');
      if (!host) return false;
      let settings;
      try { settings = await api('/api/admin/settings'); } catch { return false; }
      const state = { maintenanceMode: !!settings.maintenanceMode, storeOnline: settings.storeOnline !== false, botEnabled: settings.botEnabled !== false, salesBroadcastEnabled: !!settings.salesBroadcastEnabled };
      const card = document.createElement('section'); card.className = 'mtgx-ops-card'; card.setAttribute('aria-label','Operações rápidas da loja');
      card.innerHTML = `<div class="mtgx-ops-head"><div><div class="mtgx-ops-kicker">Operação rápida</div><h2 class="mtgx-ops-title">Controle da vitrine</h2></div><span class="mtgx-ops-state">LOJA ONLINE</span></div><div class="mtgx-ops-grid"><button type="button" class="mtgx-ops-toggle" data-key="maintenanceMode"><span class="mtgx-ops-label">Modo manutenção<small class="mtgx-ops-help">Mostra aviso de manutenção ao público</small></span><i class="mtgx-ops-switch"></i></button><button type="button" class="mtgx-ops-toggle" data-key="storeOnline"><span class="mtgx-ops-label">Vitrine disponível<small class="mtgx-ops-help">Controla o status operacional</small></span><i class="mtgx-ops-switch"></i></button><button type="button" class="mtgx-ops-toggle" data-key="botEnabled"><span class="mtgx-ops-label">Assistente Bruna<small class="mtgx-ops-help">Ativa ou pausa o atendimento automático</small></span><i class="mtgx-ops-switch"></i></button><button type="button" class="mtgx-ops-toggle" data-key="salesBroadcastEnabled"><span class="mtgx-ops-label">Aviso de vendas<small class="mtgx-ops-help">Exibe chamadas promocionais configuradas</small></span><i class="mtgx-ops-switch"></i></button></div><textarea class="mtgx-ops-message" placeholder="Mensagem exibida durante a manutenção..."></textarea><div class="mtgx-ops-actions"><button type="button" class="mtgx-ops-save">Salvar operação</button><span class="mtgx-ops-note">As alterações são aplicadas à vitrine após salvar.</span></div>`;
      card.querySelector('.mtgx-ops-message').value = settings.maintenanceMessage || 'Estamos atualizando a loja. Voltamos em instantes.';
      host.prepend(card);
      const status = card.querySelector('.mtgx-ops-state');
      const paint = () => { card.querySelectorAll('[data-key]').forEach(btn => btn.classList.toggle('is-on', !!state[btn.dataset.key])); status.textContent = state.maintenanceMode ? 'MANUTENÇÃO ATIVA' : state.storeOnline ? 'LOJA ONLINE' : 'VITRINE PAUSADA'; status.style.color = state.maintenanceMode || !state.storeOnline ? '#ffd18a' : ''; };
      card.querySelectorAll('[data-key]').forEach(btn => btn.addEventListener('click', () => { state[btn.dataset.key] = !state[btn.dataset.key]; paint(); }));
      card.querySelector('.mtgx-ops-save').addEventListener('click', async event => { const button = event.currentTarget; button.disabled = true; button.textContent = 'Salvando...'; try { await api('/api/admin/settings', { method: 'PATCH', body: JSON.stringify({ ...state, maintenanceMessage: card.querySelector('.mtgx-ops-message').value }) }); button.textContent = 'Salvo'; setTimeout(() => { button.textContent = 'Salvar operação'; button.disabled = false; }, 1400); } catch { button.textContent = 'Tentar novamente'; button.disabled = false; } });
      paint(); return true;
    };
    wait(mount);
    return;
  }
  const loadPublicStatus = async () => { try { const response = await fetch('/api/store', { cache: 'no-store' }); const settings = (await response.json()).settings || {}; if (!settings.maintenanceMode && settings.storeOnline !== false) return; const banner = document.createElement('aside'); banner.className = 'mtgx-public-status'; banner.innerHTML = `<strong>${settings.maintenanceMode ? 'Manutenção programada' : 'Vitrine pausada'}</strong><span>${settings.maintenanceMessage || 'Voltamos em instantes.'}</span>`; const style = document.createElement('style'); style.textContent = '.mtgx-public-status{position:fixed;z-index:9999;left:16px;right:16px;bottom:16px;display:grid;gap:5px;padding:13px 15px;border:1px solid rgba(255,205,130,.34);border-radius:13px;background:rgba(24,18,10,.94);box-shadow:0 15px 40px rgba(0,0,0,.35);color:#ffe0ad;font:12px system-ui}.mtgx-public-status strong{font-size:13px}.mtgx-public-status span{color:#d5b98b}@media(max-width:600px){.mtgx-public-status{bottom:10px;left:10px;right:10px}}'; document.head.appendChild(style); document.body.appendChild(banner); } catch {} };
  loadPublicStatus();
})();
/* MTGX Stores — ADM operational controls */
