(() => {
  const reduce = matchMedia('(prefers-reduced-motion: reduce)').matches;
  const lowPower = navigator.hardwareConcurrency && navigator.hardwareConcurrency <= 4;
  const motion = !reduce && !lowPower && innerWidth > 700;
  const style=document.createElement('style');style.textContent=`
    :root{--mtgx-mx:50%;--mtgx-my:30%;--mtgx-scroll:0}
    .mtgx-stage{position:relative;isolation:isolate}.mtgx-stage:after{content:"";position:fixed;z-index:999;pointer-events:none;inset:0;background:radial-gradient(420px circle at var(--mtgx-mx) var(--mtgx-my),rgba(105,78,235,.1),transparent 64%);mix-blend-mode:screen;opacity:.65}
    .mtgx-reveal{opacity:0;transform:translate3d(0,22px,0) scale(.985);transition:opacity .65s cubic-bezier(.23,1,.32,1),transform .65s cubic-bezier(.23,1,.32,1);will-change:opacity,transform}.mtgx-reveal.mtgx-visible{opacity:1;transform:none}.mtgx-stagger-1{transition-delay:30ms}.mtgx-stagger-2{transition-delay:70ms}.mtgx-stagger-3{transition-delay:110ms}.mtgx-stagger-4{transition-delay:150ms}
    .mtgx-clickable{position:relative;overflow:hidden;isolation:isolate}.mtgx-ripple{position:absolute;z-index:5;border-radius:999px;pointer-events:none;background:radial-gradient(circle,rgba(255,255,255,.42),rgba(255,255,255,.06) 48%,transparent 70%);transform:scale(0);animation:mtgx-ripple .5s ease-out forwards}.mtgx-clickable.mtgx-pressed{transform:scale(.975)!important;filter:brightness(1.08)}
    .mtgx-hover-glow{transition:filter .22s ease,box-shadow .22s ease,transform .22s ease}.mtgx-hover-glow:hover{filter:brightness(1.05);box-shadow:0 14px 32px rgba(92,65,211,.17)}.mtgx-tilt{transform-style:preserve-3d}.mtgx-scroll-line{position:fixed;z-index:1000;top:0;left:0;height:2px;width:calc(var(--mtgx-scroll) * 100%);background:linear-gradient(90deg,#22d3ee,#7c3aed,#f0abfc);box-shadow:0 0 10px rgba(124,58,237,.65);pointer-events:none}.mtgx-page-enter{animation:mtgx-page-enter .6s cubic-bezier(.23,1,.32,1) both}.mtgx-particles{position:fixed;z-index:-1;inset:0;width:100%;height:100%;pointer-events:none;opacity:.5}.mtgx-sheen{position:relative;overflow:hidden}.mtgx-sheen:before{content:"";position:absolute;z-index:2;pointer-events:none;inset:0;background:linear-gradient(110deg,transparent 38%,rgba(255,255,255,.1) 50%,transparent 62%);transform:translateX(-130%);transition:transform .55s ease}.mtgx-sheen:hover:before{transform:translateX(130%)}
    @keyframes mtgx-page-enter{from{opacity:0;transform:translateY(8px)}to{opacity:1;transform:none}}@keyframes mtgx-ripple{to{transform:scale(3.5);opacity:0}}@keyframes mtgx-attention{0%,100%{box-shadow:0 0 0 0 rgba(34,211,238,.16)}50%{box-shadow:0 0 0 7px rgba(34,211,238,0)}}.mtgx-attention{animation:mtgx-attention 3.4s ease-in-out infinite}
    @media(max-width:700px){.mtgx-stage:after{display:none}.mtgx-tilt{transform:none!important}.mtgx-particles{display:none}.mtgx-reveal{opacity:1!important;transform:none!important;transition:none!important}.mtgx-sheen:before{display:none}.mtgx-attention{animation:none!important}.mtgx-clickable.mtgx-pressed{transform:none!important}.mtgx-scroll-line{display:none}}@media(prefers-reduced-motion:reduce){.mtgx-stage:after,.mtgx-particles{display:none}.mtgx-reveal{opacity:1;transform:none;transition:none}.mtgx-ripple,.mtgx-scroll-line{display:none}.mtgx-clickable.mtgx-pressed{transform:none!important}}
  `;document.head.appendChild(style);document.body.classList.add('mtgx-stage','mtgx-page-enter');
  const progress=document.createElement('div');progress.className='mtgx-scroll-line';document.body.appendChild(progress);
  let raf=0, active=!document.hidden, lastScroll=-1, lastX=-1,lastY=-1;
  const schedule=fn=>{if(!raf&&active)raf=requestAnimationFrame(()=>{raf=0;fn()})};
  document.addEventListener('visibilitychange',()=>{active=!document.hidden;if(!active&&raf){cancelAnimationFrame(raf);raf=0}});
  if(motion&&!lowPower&&innerWidth>700){const canvas=document.createElement('canvas');canvas.className='mtgx-particles';document.body.prepend(canvas);const ctx=canvas.getContext('2d',{alpha:true});let dots=[],w=0,h=0;const resize=()=>{const dpr=Math.min(devicePixelRatio||1,1.5);w=innerWidth;h=innerHeight;canvas.width=w*dpr;canvas.height=h*dpr;canvas.style.width=w+'px';canvas.style.height=h+'px';ctx.setTransform(dpr,0,0,dpr,0,0);dots=Array.from({length:Math.min(22,Math.max(12,Math.floor(w/55)))},()=>({x:Math.random()*w,y:Math.random()*h,r:Math.random()*1.3+.3,vx:(Math.random()-.5)*.1,vy:(Math.random()-.5)*.1,a:Math.random()*.3+.08}))};let last=0;const draw=t=>{if(t-last<45){requestAnimationFrame(draw);return}last=t;if(active){ctx.clearRect(0,0,w,h);for(const p of dots){p.x=(p.x+p.vx+w)%w;p.y=(p.y+p.vy+h)%h;ctx.beginPath();ctx.arc(p.x,p.y,p.r,0,Math.PI*2);ctx.fillStyle=`rgba(130,150,255,${p.a})`;ctx.fill()}}requestAnimationFrame(draw)};addEventListener('resize',resize,{passive:true});resize();requestAnimationFrame(draw)}
  const revealSelector='.hero-copy,.hero-aside,main > section,section > .section-heading,.product-card,.notice-card,.portfolio-card,.channel-card,.quick-card,.metric-card,.chart-card,.inbox-card,.list-card,.admin-section,.admin-topbar';let observer,seq=0;
  const animate=(root=document)=>{if(!observer&&'IntersectionObserver'in window)observer=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('mtgx-visible');observer.unobserve(e.target)}}),{threshold:.08,rootMargin:'0px 0px -18px'});root.querySelectorAll?.(revealSelector).forEach(el=>{if(el.dataset.mtgxReveal)return;el.dataset.mtgxReveal='1';el.classList.add('mtgx-reveal',`mtgx-stagger-${(seq++%4)+1}`);observer?observer.observe(el):el.classList.add('mtgx-visible')});root.querySelectorAll?.('.product-card,.portfolio-card,.hero-card,.notice-card,.channel-card,.quick-card').forEach(el=>el.classList.add('mtgx-sheen'));root.querySelectorAll?.('button,a[href],[role="button"],.product-card,.notice-card,.portfolio-card,.channel-card,.quick-card').forEach(el=>{if(el.dataset.mtgxClick)return;el.dataset.mtgxClick='1';el.classList.add('mtgx-clickable','mtgx-hover-glow');el.addEventListener('pointerdown',e=>{el.classList.add('mtgx-pressed');const r=el.getBoundingClientRect(),size=Math.max(r.width,r.height)*.45,ri=document.createElement('span');ri.className='mtgx-ripple';ri.style.cssText=`width:${size}px;height:${size}px;left:${e.clientX-r.left-size/2}px;top:${e.clientY-r.top-size/2}px`;el.appendChild(ri);setTimeout(()=>{el.classList.remove('mtgx-pressed');ri.remove()},520)},{passive:true})});if(innerWidth>700&&!lowPower)root.querySelectorAll?.('.product-card,.portfolio-card,.channel-card,.quick-card,.hero-card,.metric-card').forEach(el=>{if(el.dataset.mtgxTilt)return;el.dataset.mtgxTilt='1';el.classList.add('mtgx-tilt');el.addEventListener('pointermove',e=>{const r=el.getBoundingClientRect(),x=(e.clientX-r.left)/r.width,y=(e.clientY-r.top)/r.height;el.style.transform=`perspective(900px) rotateX(${(0.5-y)*3}deg) rotateY(${(x-.5)*4}deg) translateY(-3px)`},{passive:true});el.addEventListener('pointerleave',()=>el.style.transform='',{passive:true})});root.querySelectorAll?.('.hero-proof,.hero-direct,.notice-icon,.metric-icon,.chat-toggle').forEach(el=>el.classList.add('mtgx-attention'))};
  const onMotion=e=>{if(!motion||!active)return;if(e.clientX===lastX&&e.clientY===lastY)return;lastX=e.clientX;lastY=e.clientY;schedule(()=>{document.documentElement.style.setProperty('--mtgx-mx',`${lastX}px`);document.documentElement.style.setProperty('--mtgx-my',`${lastY}px`);})};const onScroll=()=>schedule(()=>{const max=Math.max(1,document.documentElement.scrollHeight-innerHeight),v=Math.min(1,scrollY/max);if(Math.abs(v-lastScroll)>.004){lastScroll=v;document.documentElement.style.setProperty('--mtgx-scroll',v)}});if(motion){addEventListener('pointermove',onMotion,{passive:true});addEventListener('scroll',onScroll,{passive:true})}animate();let pending=false;new MutationObserver(()=>{if(pending)return;pending=true;requestAnimationFrame(()=>{pending=false;animate()})}).observe(document.body,{childList:true,subtree:true});
})();
