(() => {
  const css = document.createElement('style');
  css.textContent = `
    .verified-profile{align-items:center!important;vertical-align:middle!important;transform:translateY(0)!important;cursor:pointer!important}
    .verified-profile .inline-icon{vertical-align:middle!important;margin-left:3px!important;position:relative;top:0!important}
    .mtgx-profile-modal{position:fixed;z-index:2000;inset:0;display:grid;place-items:center;padding:18px;background:rgba(0,0,0,.82);backdrop-filter:blur(18px);opacity:0;pointer-events:none;transition:opacity .3s ease}
    .mtgx-profile-modal.open{opacity:1;pointer-events:auto}
    .mtgx-profile-shell{position:relative;width:min(470px,100%);max-height:min(720px,92vh);overflow:auto;border:1px solid rgba(255,255,255,.28);border-radius:22px;background:linear-gradient(145deg,#15171a,#060708 65%);box-shadow:0 30px 100px rgba(0,0,0,.78),0 0 55px rgba(71,100,230,.16);transform:translateY(18px) scale(.96);transition:transform .4s cubic-bezier(.23,1,.32,1)}
    .mtgx-profile-modal.open .mtgx-profile-shell{transform:translateY(0) scale(1)}
    .mtgx-profile-cover{height:170px;background:linear-gradient(180deg,rgba(0,0,0,.08) 20%,#090909 100%),var(--profile-cover) center/cover;position:relative;isolation:isolate;overflow:hidden}
    .mtgx-profile-cover:before{content:"";position:absolute;inset:0;background:linear-gradient(115deg,transparent 28%,rgba(255,255,255,.18) 48%,transparent 62%);transform:translateX(-120%);animation:mtgx-cover-sheen 5.5s ease-in-out infinite;mix-blend-mode:screen;z-index:1}
    .mtgx-profile-cover:after{content:"";position:absolute;inset:0;background:radial-gradient(circle at 20% 18%,rgba(146,203,255,.28) 0 1px,transparent 2px),radial-gradient(circle at 78% 35%,rgba(255,255,255,.2) 0 1px,transparent 2px),linear-gradient(180deg,transparent 45%,rgba(0,0,0,.3));opacity:.7;z-index:1;animation:mtgx-cover-drift 8s ease-in-out infinite alternate}
    @keyframes mtgx-cover-sheen{0%,35%{transform:translateX(-120%);opacity:0}52%{opacity:.8}72%,100%{transform:translateX(120%);opacity:0}}
    @keyframes mtgx-cover-drift{to{transform:translate3d(5px,-4px,0);opacity:.45}}
    .mtgx-profile-close{position:absolute;right:14px;top:14px;width:34px;height:34px;border:1px solid rgba(255,255,255,.32);border-radius:50%;color:#fff;background:rgba(0,0,0,.45);font-size:20px;cursor:pointer;z-index:3}
    .mtgx-profile-body{padding:0 24px 26px}.mtgx-profile-avatar{width:92px;height:92px;margin-top:-46px;position:relative;border:3px solid #111;border-radius:50%;object-fit:cover;box-shadow:0 0 0 2px #4f9cff,0 0 30px rgba(57,125,255,.4);animation:mtgx-avatar-pulse 3.8s ease-in-out infinite}@keyframes mtgx-avatar-pulse{50%{box-shadow:0 0 0 3px #a9d9ff,0 0 36px rgba(57,125,255,.58)}}
    .mtgx-profile-name{display:flex;align-items:center;gap:7px;margin:13px 0 3px;color:#fff;font-size:23px;font-weight:700}.mtgx-profile-name svg{width:18px;height:18px;padding:3px;border-radius:50%;background:#3c8cff;color:#fff}
    .mtgx-profile-handle{color:#9ca7bd;font-size:12px}.mtgx-profile-bio{color:#deded8;line-height:1.55;margin:18px 0 16px;font-size:14px}.mtgx-profile-meta{display:flex;gap:18px;color:#aeb2bd;font-size:12px;margin-bottom:20px}.mtgx-profile-meta strong{color:#fff;font-size:16px;display:block}.mtgx-profile-links{display:grid;gap:9px}.mtgx-profile-links a{display:flex;align-items:center;justify-content:space-between;padding:12px 14px;border:1px solid rgba(255,255,255,.14);border-radius:10px;color:#fff;background:rgba(255,255,255,.045);text-decoration:none;transition:transform .2s ease,background .2s ease,border-color .2s ease}.mtgx-profile-links a:hover{background:rgba(91,122,255,.14);border-color:rgba(117,159,255,.5);transform:translateX(3px)}
    @media(prefers-reduced-motion:reduce){.mtgx-profile-cover:before,.mtgx-profile-cover:after,.mtgx-profile-avatar{animation:none}.mtgx-profile-links a{transition:none}}
  `;
  document.head.appendChild(css);
  let settings = {};
  const fallback = {storeName:'MTGX Stores',verifiedName:'Mtgz',adminAvatarUrl:'/profile-cover.jpg',profileCoverUrl:'/1001256585.gif',profileUsername:'@mtgxstores',profileBio:'Experiências digitais, ideias que viram movimento e uma curadoria feita para quem não aceita o comum.',profileFollowers:'1,2 mil',profileFollowing:'128',profilePosts:'24',profileLocation:'Brasil',verifiedBadge:true};
  const getSettings = async () => { try { const res=await fetch('/api/store'); const data=await res.json(); settings={...fallback,...(data.settings||{})}; } catch { settings=fallback; } };
  const icon = '<svg viewBox="0 0 24 24" aria-label="Verificado"><path fill="currentColor" d="M12 2l2.2 1.8 2.8-.2 1.1 2.6 2.5 1.3-.6 2.8 1.4 2.4-1.9 2.1.2 2.8-2.7 1-1.3 2.5-2.8-.6L12 22l-2.2-1.8-2.8.2-1.1-2.6-2.5-1.3.6-2.8L2.6 11l1.9-2.1-.2-2.8 2.7-1 1.3-2.5 2.8.6L12 2zm-1.1 13.6l5.8-5.8-1.4-1.4-4.4 4.4-2.1-2.1-1.4 1.4 3.5 3.5z"/></svg>';
  const ensureModal = () => { if (document.querySelector('.mtgx-profile-modal')) return; const s=()=>({...fallback,...settings}); const el=document.createElement('div'); el.className='mtgx-profile-modal'; el.innerHTML='<div class="mtgx-profile-shell" role="dialog" aria-label="Perfil da loja"><div class="mtgx-profile-cover"></div><button class="mtgx-profile-close" aria-label="Fechar perfil">×</button><div class="mtgx-profile-body"><img class="mtgx-profile-avatar" alt="Foto do perfil"><div class="mtgx-profile-name"></div><div class="mtgx-profile-handle"></div><p class="mtgx-profile-bio"></p><div class="mtgx-profile-meta"><span><strong class="posts"></strong>publicações</span><span><strong class="followers"></strong>seguidores</span><span><strong class="following"></strong>seguindo</span></div><div class="mtgx-profile-links"><a class="profile-wa" target="_blank" rel="noreferrer"><span>Falar com a loja</span><b>↗</b></a><a class="profile-location"><span>Localização</span><b></b></a></div></div></div>'; document.body.appendChild(el); const update=()=>{const x=s();el.querySelector('.mtgx-profile-cover').style.setProperty('--profile-cover',`url('${x.profileCoverUrl||x.backgroundUrl||fallback.profileCoverUrl}')`);el.querySelector('.mtgx-profile-avatar').src=x.adminAvatarUrl||fallback.adminAvatarUrl;el.querySelector('.mtgx-profile-name').innerHTML=`${x.verifiedName||x.storeName} ${x.verifiedBadge?icon:''}`;el.querySelector('.mtgx-profile-handle').textContent=x.profileUsername||'@mtgxstores';el.querySelector('.mtgx-profile-bio').textContent=x.profileBio||fallback.profileBio;el.querySelector('.posts').textContent=x.profilePosts||'0';el.querySelector('.followers').textContent=x.profileFollowers||'0';el.querySelector('.following').textContent=x.profileFollowing||'0';el.querySelector('.profile-wa').href=x.whatsappUrl||'#';el.querySelector('.profile-location b').textContent=x.profileLocation||'Brasil';}; update(); el.querySelector('.mtgx-profile-close').onclick=()=>el.classList.remove('open');el.addEventListener('click',e=>{if(e.target===el)el.classList.remove('open')}); document.addEventListener('keydown',e=>{if(e.key==='Escape')el.classList.remove('open')}); el._update=update; };
  const bind = () => { ensureModal(); document.querySelectorAll('.verified-profile').forEach(el=>{if(el.dataset.profileBound)return;el.dataset.profileBound='1';el.addEventListener('click',()=>{const modal=document.querySelector('.mtgx-profile-modal');modal._update?.();modal.classList.add('open');});}); };
  getSettings().finally(bind); let pending=false; new MutationObserver(()=>{if(pending)return;pending=true;requestAnimationFrame(()=>{pending=false;bind();});}).observe(document.body,{childList:true,subtree:true});
})();
