(() => {
  const css = document.createElement('style');
  css.textContent = `
    .verified-profile{align-items:center!important;vertical-align:middle!important;transform:translateY(0)!important;cursor:pointer!important}
    .verified-profile .inline-icon{vertical-align:middle!important;margin-left:3px!important;position:relative;top:0!important}
    .mtgx-profile-modal{position:fixed;z-index:2000;inset:0;display:grid;place-items:center;padding:18px;background:rgba(0,0,0,.78);backdrop-filter:blur(16px);opacity:0;pointer-events:none;transition:opacity .3s ease}
    .mtgx-profile-modal.open{opacity:1;pointer-events:auto}
    .mtgx-profile-shell{position:relative;width:min(470px,100%);max-height:min(720px,92vh);overflow:auto;border:1px solid rgba(255,255,255,.28);border-radius:22px;background:linear-gradient(145deg,#1a1a1a,#080808 65%);box-shadow:0 30px 100px rgba(0,0,0,.75),0 0 55px rgba(71,100,230,.16);transform:translateY(18px) scale(.96);transition:transform .4s cubic-bezier(.23,1,.32,1)}
    .mtgx-profile-modal.open .mtgx-profile-shell{transform:translateY(0) scale(1)}
    .mtgx-profile-cover{height:170px;background:linear-gradient(180deg,rgba(5,8,14,.12) 20%,#090909 100%),var(--profile-cover) center/cover;position:relative}
    .mtgx-profile-cover-meta{position:absolute;z-index:2;left:16px;right:62px;top:14px;display:flex;align-items:center;justify-content:space-between;gap:8px;color:rgba(231,242,255,.78);font:600 8px ui-monospace,SFMono-Regular,Menlo,monospace;letter-spacing:.1em;text-transform:uppercase;text-shadow:0 1px 8px rgba(0,0,0,.8)}
    .mtgx-profile-online{display:inline-flex;align-items:center;gap:5px;color:#a8f3c6}.mtgx-profile-online i{width:6px;height:6px;border-radius:50%;background:#7aeca9;box-shadow:0 0 0 3px rgba(122,236,169,.15),0 0 10px #7aeca9}
    .mtgx-profile-close{position:absolute!important;z-index:4!important;right:14px;top:14px;width:36px;height:36px;border:1px solid rgba(255,255,255,.38);border-radius:50%;color:#fff;background:rgba(5,9,16,.66);font-size:20px;line-height:1;cursor:pointer;backdrop-filter:blur(10px);box-shadow:0 8px 22px rgba(0,0,0,.35)}
    .mtgx-profile-body{padding:0 24px 26px}.mtgx-profile-avatar{width:92px;height:92px;margin-top:-46px;position:relative;border:3px solid #111;border-radius:50%;object-fit:cover;box-shadow:0 0 0 2px #4f9cff,0 0 30px rgba(57,125,255,.4)}
    .mtgx-profile-name{display:flex;align-items:center;gap:7px;margin:13px 0 3px;color:#fff;font-size:23px;font-weight:700}.mtgx-profile-name svg{width:18px;height:18px;padding:3px;border-radius:50%;background:#3c8cff;color:#fff}
    .mtgx-profile-handle{color:#9ca7bd;font-size:12px}.mtgx-profile-bio{color:#deded8;line-height:1.55;margin:18px 0 16px;font-size:14px}.mtgx-profile-meta{display:flex;gap:18px;color:#aeb2bd;font-size:12px;margin-bottom:20px}.mtgx-profile-meta strong{color:#fff;font-size:16px;display:block}.mtgx-profile-links{display:grid;gap:9px}.mtgx-profile-links a{display:flex;align-items:center;justify-content:space-between;padding:12px 14px;border:1px solid rgba(255,255,255,.14);border-radius:10px;color:#fff;background:rgba(255,255,255,.045);text-decoration:none}.mtgx-profile-links a:hover{background:rgba(91,122,255,.14);border-color:rgba(117,159,255,.5)}
  `;
  document.head.appendChild(css);
  let settings = {};
  const fallback = {storeName:'MTGX Stores',verifiedName:'Mtgz',adminAvatarUrl:'/profile-cover.jpg',profileCoverUrl:'/profile-cover.jpg',profileUsername:'@mtgxstores',profileBio:'Experiências digitais, ideias que viram movimento e uma curadoria feita para quem não aceita o comum.',profileFollowers:'1,2 mil',profileFollowing:'128',profilePosts:'24',profileLocation:'Brasil',verifiedBadge:true};
  const getSettings = async () => { try { const res=await fetch('/api/store'); const data=await res.json(); settings={...fallback,...(data.settings||{})}; } catch { settings=fallback; } };
  const icon = '<svg viewBox="0 0 24 24" aria-label="Verificado"><path fill="currentColor" d="M12 2l2.2 1.8 2.8-.2 1.1 2.6 2.5 1.3-.6 2.8 1.4 2.4-1.9 2.1.2 2.8-2.7 1-1.3 2.5-2.8-.6L12 22l-2.2-1.8-2.8.2-1.1-2.6-2.5-1.3.6-2.8L2.6 11l1.9-2.1-.2-2.8 2.7-1 1.3-2.5 2.8.6L12 2zm-1.1 13.6l5.8-5.8-1.4-1.4-4.4 4.4-2.1-2.1-1.4 1.4 3.5 3.5z"/></svg>';
  const ensureModal = () => { if (document.querySelector('.mtgx-profile-modal')) return; const s=()=>({...fallback,...settings}); const el=document.createElement('div'); el.className='mtgx-profile-modal'; el.innerHTML=`<div class="mtgx-profile-shell" role="dialog" aria-label="Perfil da loja"><div class="mtgx-profile-cover"><div class="mtgx-profile-cover-meta"><span>MTGX STORES · PERFIL VERIFICADO</span><span class="mtgx-profile-online"><i></i> ONLINE</span></div></div><button class="mtgx-profile-close" aria-label="Fechar perfil">×</button><div class="mtgx-profile-body"><img class="mtgx-profile-avatar" alt="Foto do perfil"><div class="mtgx-profile-name"></div><div class="mtgx-profile-handle"></div><p class="mtgx-profile-bio"></p><div class="mtgx-profile-meta"><span><strong class="posts"></strong>publicações</span><span><strong class="followers"></strong>seguidores</span><span><strong class="following"></strong>seguindo</span></div><div class="mtgx-profile-links"><a class="profile-wa" target="_blank" rel="noreferrer"><span>Falar com a loja</span><b>↗</b></a><a class="profile-location"><span>Localização</span><b></b></a></div></div></div>`; document.body.appendChild(el); const update=()=>{const x=s();el.querySelector('.mtgx-profile-cover').style.setProperty('--profile-cover',`url('${x.profileCoverUrl||x.backgroundUrl||fallback.profileCoverUrl}')`);el.querySelector('.mtgx-profile-avatar').src=x.adminAvatarUrl||fallback.adminAvatarUrl;el.querySelector('.mtgx-profile-name').innerHTML=`${x.verifiedName||x.storeName} ${x.verifiedBadge?icon:''}`;el.querySelector('.mtgx-profile-handle').textContent=x.profileUsername||'@mtgxstores';el.querySelector('.mtgx-profile-bio').textContent=x.profileBio||fallback.profileBio;el.querySelector('.posts').textContent=x.profilePosts||'0';el.querySelector('.followers').textContent=x.profileFollowers||'0';el.querySelector('.following').textContent=x.profileFollowing||'0';el.querySelector('.profile-wa').href=x.whatsappUrl||'#';el.querySelector('.profile-location b').textContent=x.profileLocation||'Brasil';}; update(); el.querySelector('.mtgx-profile-close').onclick=()=>el.classList.remove('open');el.addEventListener('click',e=>{if(e.target===el)el.classList.remove('open')}); document.addEventListener('keydown',e=>{if(e.key==='Escape')el.classList.remove('open')}); el._update=update; };
  const bind = () => { ensureModal(); document.querySelectorAll('.verified-profile').forEach(el=>{if(el.dataset.profileBound)return;el.dataset.profileBound='1';el.addEventListener('click',()=>{const modal=document.querySelector('.mtgx-profile-modal');modal._update?.();modal.classList.add('open');});}); };
  const hasProfileTrigger = records => records.some(record => [...record.addedNodes].some(node => node.nodeType === 1 && (node.matches?.('.verified-profile') || node.querySelector?.('.verified-profile'))));
  getSettings().finally(()=>{bind(); document.querySelector('.mtgx-profile-modal')?._update?.();});
  new MutationObserver(records=>{ if (hasProfileTrigger(records)) bind(); }).observe(document.body,{childList:true,subtree:true});
})();
